# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bastille Blockchain Solutions
tagline: Amat Victoria Curam

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Navigation
navigation:
- title: Fr
  url: /fr
- title: En
  url: /
- title: Zh
  url: /zh

# Contact
author:
  name:         "Samy Gejzenblozen"
  email:        "contact@bastille-blockchain.com"
  twitter:      "sm2g"
  instagram:    "sm2g"
  github:       "sm2g"
  facebook:     "samy.gejzenblozen"
  linkedin:     "samy.gejzenblozen"

# address
address: "Place de la Bastille"
zipcode: 75011
city: "Paris"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
