### FR ###

- title: Interface de paiement Crypto
  lang: fr
  bg: crypto
  description: "Connectez votre vitrine en ligne à nos interfaces de paiement en crypto monnaie sur mesure et élargissez votre spectre de paiement."

- title: Formation Blockchain
  lang: fr
  bg: lecture
  description: "Que ce soit via nos formations en ligne, ou directement en face-à-face, appréhendez les concepts fondamentaux des technologies Blockchain & DLT."

- title: Réalisation POC Blockchain
  lang: fr
  bg: code
  description: "De la sélection des choix technologies selon votre cas d'usage à sa réalisation, nous vous accompagnons lors de la concrétisation de votre projet Blockchain & DLT."

### EN ###

- title: Crypto payment interface
  lang: en
  bg: crypto
  description: "Connect your online storefront to our custom cryptocurrency payment interfaces and broaden your payment spectrum."

- title: Blockchain Training
  lang: en
  bg: lecture
  description: "Whether through our online training, or directly face-to-face, apprehend the fundamental concepts of Blockchain & DLT technologies."

- title: Smart contract & Blockchain project 
  lang: en
  bg: code
  description: "From the selection of technology according to your use case to its realization, we provide technical support in the realization of your DLT & Blockchain project."

### ZH ###

- title: Crypto payment interface
  lang: zh
  bg: crypto
  description: "Connect your online storefront to our custom cryptocurrency payment interfaces and broaden your payment spectrum."

- title: Blockchain Training
  lang: zh
  bg: lecture
  description: "Whether through our online training, or directly face-to-face, apprehend the fundamental concepts of Blockchain & DLT technologies."

- title: Réalisation POC Blockchain
  lang: zh
  bg: code
  description: "From the selection of technology according to your use case to its realization, we provide technical support in the realization of your DLT & Blockchain project."
